# Assignment 2.

The file `tms_mapping.csv` contains results of TMS mapping of 10 participants' left hemisphere language areas. To perform the mapping a grid of targets was used, similar to this one:

<img src="https://drive.google.com/uc?export=view&id=15fBf7Qk-f_tTb7pvyvn29MPWV4ZseCR9" style="height: 200px; width: auto">


The mapping procedure was performed on 10 individuals. Thus, each of 10 grids (13 x 13 targets) contains individual responses to a single 10 Hz rTMS train. `1` means that the rTMS application to a particular site interfered with participant's speech; `0` means failure of any language interference.

Your task is: 
1. To overlap all grids so that they represent probability (%) of speech interference in all sites - use NumPy array.
2. To replace all subthreshold probabilities with `0` (as a threshold use 70% probability).
3. To add **x** and **y** coordinates, so that the central point of the grid is represented as `x = 0` and `y = 0`:
    * Add x axis (ranging from -6 to 6) on the top of the array
    * Add y axis (ranging from -6 to 6) on the left side of the array<br><br>
    
   The final array should look like this:
    
    ```
    [
     [  0  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6]
     [ -6   0   0   0   0   0   0   0   0   0   0   0   0   0]
     [ -5   0   0   0   0   0   0   0   0   0   0   0   0   0]
     [ -4   0   0   0   0   0   0   0   0   0   0   0   0   0]
     [ -3   0   0   0   0   0   0   0   0   0   0   0   0   0]
     [ -2   0   0   0   0   0   0   0   0   0   0   0   0   0]
     [ -1   0   0   0   0   0   0   0   0  70   0   0   0   0]
     [  0   0   0   0   0   0   0  70  70  80  70   0   0   0]
     [  1   0   0   0   0   0  70  70  90  90  90   0   0   0]
     [  2   0   0  80  90   0  70  90  70  90 100  90   0   0]
     [  3   0  90 100 100   0   0   0 100  90 100   0   0   0]
     [  4   0   0 100   0  70  70   0  90  90   0  80   0   0]
     [  5   0   0   0   0   0   0   0   0   0   0   0   0   0]
     [  6   0   0   0   0   0   0   0   0   0   0   0   0   0]
    ]
    ```
    
4. To display coordinates of all sites/targets where probabilities were maximal as a table:

    ```
    Table 1. Coordinates of sites with highest probability of speech interference:

    |______Nr_______|_______X_______|_______Y_______|_____Area______|
    |       1       |       3       |       2       |   Wernicke    |
    |       2       |      -4       |       3       |     Broca     |
    |       3       |      -3       |       3       |     Broca     |
    |       4       |       1       |       3       |   Wernicke    |
    |       5       |       3       |       3       |   Wernicke    |
    |       6       |      -4       |       4       |     Broca     |
    ```

    <br><br>For language areas use these coordinates:
    1. **Broca's area** is defined as a rectangular area with coordinates:
       - top left: x = -5, y = 2
       - bottom right: x = -3, y = 4<br><br>
    2. **Wernicke's area** is defined as a rectangular area with coordinates:
       - top left: x = 1, y = 1
       - bottom right: x = 3, y = 4<br><br>
    
HINTS:
* In order to read the file directly to a NumPy array you may use: 
```python
   my_array = np.genfromtxt(path_to_file, delimiter=';', dtype = int)
```
* Preview the CSV file and see how the data is arranged, before you start writing the code. You will probably have to slice the original array;
* Array vectorization (scalar and array-array), aggregation methods, as well as boolean indexing will be very helpful;
* To create a table, f-string will be ideal.

In [21]:
### Configure IPython shell to print all outputs generated in a code cell
### --------------------------------------------------------------------------
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np

# this will ensure proper alignment of arrays in the output of jupyter notebook (without wrapping)
np.set_printoptions(linewidth = 120)


#============================== your code here: ==============================

path_to_file = "tms_mapping.csv"

my_array = np.genfromtxt(path_to_file, delimiter=';', dtype = int)

broca_topleft = (-5, 2)

broca_bottomright = (-3, 4)

wernicke_topleft = (1, 1)

wernicke_bottomright = (3, 4)
#=============================================================================


### Probability (%) of speech interference in all sites


In [22]:
def slice_matrix(sample_size, init_array):

    sliced_data = []

    for i in range(sample_size):

        sliced_data.append(init_array[1 + 14*i:14 + 14*i,: ])

    return sliced_data


data = slice_matrix(10, my_array)


def sum_arrays(data_arr):

    sol = np.zeros( (13,13) )

    for elt in data_arr:

        sol += elt

    return sol


def calc_prob(data_arr, sample_size):

    return ((sum_arrays(data_arr)/sample_size)*100).astype(int)


data = calc_prob(data, 10)

data[data < 70] = 0


def add_index(data_arr):

    rows = np.arange(-6, 7, 1).reshape((13, 1))

    columns = np.concatenate( ( np.array([0]), np.arange(-6, 7, 1)) )

    sol = np.hstack( (rows, data_arr) )

    sol = np.vstack( (columns, sol ))

    return sol


data = add_index(data)

print(" Table 1. Coordinates of sites with highest probability of speech interference:")


coord = np.where(data == 100)
indx = (zip(coord[0], coord[1]))


header = ["Nr", "X", "Y", "Area"]

print(f"|{header[0]:_^17}|{header[1]:_^17}|{header[2]:_^17}|{header[3]:_^17}|")

i = 1

def wernicke_or_broca(x, y):

    #print(y-7, x-7)


    if y - 7 in range(-5, -2) and x - 7 in range(2, 5):

        #print("B")

        return "Broca"

    elif y - 7 in range(1, 4) and x - 7 in range(1, 5):

        #print("w")

        return "Wernicke"

    else:

        return ""


for elt in indx:

    area = wernicke_or_broca(elt[0], elt[1])

    if area != "":

        print(f"|{i:_^17}|{elt[1] - 7:_^17}|{elt[0] - 7:_^17}|{wernicke_or_broca(elt[0], elt[1]):_^17}|")

    i += 1

 Table 1. Coordinates of sites with highest probability of speech interference:
|_______Nr________|________X________|________Y________|______Area_______|
|________1________|________3________|________2________|____Wernicke_____|
|________2________|_______-4________|________3________|______Broca______|
|________3________|_______-3________|________3________|______Broca______|
|________4________|________1________|________3________|____Wernicke_____|
|________5________|________3________|________3________|____Wernicke_____|
|________6________|_______-4________|________4________|______Broca______|
